--Create Database "FOOD_MARKET_DB"
USE DATABASE FOOD_MARKET_DB;

-- Create Schemas:
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CLEAN;

-- Use an existing warehouse, or create a small one:
CREATE WAREHOUSE IF NOT EXISTS FM_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

USE WAREHOUSE FM_WH;
USE SCHEMA RAW;