CREATE OR REPLACE TABLE Food_Market_DB.RAW.ROW_COUNT (
  INDEX_NO NUMBER AUTOINCREMENT START 1 INCREMENT 1,
  NO_OF_ROWS NUMBER,
  DATE TIMESTAMP_NTZ,
  NO_OF_ROWS_ADDED NUMBER,
  NO_OF_ROWS_IN_TRANSFORMED_TABLE NUMBER
);