CREATE OR REPLACE TASK Food_Market_DB.RAW.SNOWPARK_TRANSFORM_TASK
  WAREHOUSE = COMPUTE_WH
  SCHEDULE = 'USING CRON 0 12 * * * UTC'   -- daily 12:00 UTC
AS
  CALL Food_Market_DB.RAW.SNOWPARK_TRANSFORM();

ALTER TASK Food_Market_DB.RAW.SNOWPARK_TRANSFORM_TASK RESUME;